name: github_embeddings
description: Manages a local embeddings database for github embeddings
environment:
  sdk: ^3.10.0
dependencies:
  args: ^2.7.0
  crypto: ^3.0.7
  github: ^9.25.0
  google_generative_ai: ^0.4.7
  path: ^1.9.1
